# mysql connect configuration
mysql:
  path: "127.0.0.1"
  port: "3306"
  config: "parseTime=true&loc=Local"  # 一定要设置时区
  db-name: "go_game"
  username: "root"
  password: "12345678"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[lf/go-my-start]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true