# mysql connect configuration
mysql:
  path: "127.0.0.1"
  port: "3306"
  config: ""
  db-name: "go_game"
  username: "root"
  password: "12345678"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false